### ISSUE TITLE
Can not Login

### ISSUE THREAD

**Issue by davidtavarez** [aldenquimby/parse-csharp#10]
When I try to do Login it throws an Exception.

![screen shot 2014-08-11 at 4 15 33 pm](https://cloud.githubusercontent.com/assets/337107/3882127/59ec3e76-2194-11e4-90db-a330ee53a2f1.png)
![screen shot 2014-08-11 at 4 15 57 pm](https://cloud.githubusercontent.com/assets/337107/3882129/5d4a5850-2194-11e4-9ac3-e0de465bd602.png)

**Comment by aldenquimby** [comment]
That's strange, it seems to work for me as well as others that are using the library.

What happens when you run the tests in `ParseRestClientTests`? And specifically try running the method `TestObjects`. You'll need to fill in the following fields at the top of the test class:

```
private const string APP_ID = "";
private const string REST_API_KEY = "";
private const string VALID_USER_ID1 = "";
```

**Comment by davidtavarez** [comment]
Oh, I just clone te repo and it works, but SessionToken is still empty.
![screen shot 2014-08-12 at 10 00 56 am](https://cloud.githubusercontent.com/assets/337107/3891368/485ca00c-2229-11e4-8699-039c28d7a60b.png)

**Comment by davidtavarez** [comment]
I fixed this and create a pull request: https://github.com/aldenquimby/parse-csharp/pull/11
