### ISSUE TITLE
Signup method doesn't return User neither SessionToken

### ISSUE THREAD

**Issue by davidtavarez** [aldenquimby/parse-csharp#7]
Signup method is working fine, but it returns and empty SessionToken.

![screen shot 2014-08-11 at 9 22 38 am](https://cloud.githubusercontent.com/assets/337107/3876299/ea61497c-215a-11e4-9dde-7f25c542b7ca.png)

**Comment by aldenquimby** [comment]
Archiving repo now that Parse re-architected and this hasn't been maintained
